<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'text' => 'Qual campeão de Águas de Sentina é um atirador de elite com uma pistola que atira moedas de ouro?',
                'correct_answer' => 'Gangplank',
                'options' => json_encode(['Twisted Fate', 'Graves', 'Miss Fortune', 'Gangplank']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual é o nome do Kraken gigante que reside nas profundezas de Águas de Sentina e que é adorado por Illaoi?',
                'correct_answer' => 'Nagakabouros',
                'options' => json_encode(['Nagakabouros', 'Ornn', 'Volibear', 'Aurelion Sol']),
                'difficulty' => 'medium',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual campeão é um caçador de monstros marinhos com um gancho e uma âncora?',
                'correct_answer' => 'Nautilus',
                'options' => json_encode(['Pyke', 'Fizz', 'Nautilus', 'Gangplank']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Quem é o "Açougueiro de Águas de Sentina", um demônio que caça assassinos de almas?',
                'correct_answer' => 'Pyke',
                'options' => json_encode(['Nautilus', 'Pyke', 'Twisted Fate', 'Miss Fortune']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual é o nome do capitão pirata que foi traído e morto, mas retornou como um fantasma sedento por vingança?',
                'correct_answer' => 'Gangplank',
                'options' => json_encode(['Miss Fortune', 'Twisted Fate', 'Graves', 'Gangplank']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual campeã é a Capitã da tripulação do Cólera da Estrela da Manhã e busca vingança contra Gangplank?',
                'correct_answer' => 'Miss Fortune',
                'options' => json_encode(['Illaoi', 'Miss Fortune', 'Seraphine', 'Ahri']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual é a moeda local de Águas de Sentina?',
                'correct_answer' => 'Doblo de cobra',
                'options' => json_encode(['Doblo de cobra', 'Moeda de ouro', 'Pedra de fogo', 'Escama de dragão']),
                'difficulty' => 'medium',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual criatura lendária é frequentemente caçada por piratas em Águas de Sentina, valorizada por sua pele e ossos?',
                'correct_answer' => 'Leviatã',
                'options' => json_encode(['Dragão do Mar', 'Serpente do Mar', 'Leviathan', 'Kraken']),
                'difficulty' => 'medium',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual o festival anual em Águas de Sentina, onde os mortos são honrados e fantasmas retornam?',
                'correct_answer' => 'O Festival das Crianças',
                'options' => json_encode(['O Festival do Sol', 'O Festival da Lua', 'O Festival das Crianças', 'O Festival da Colheita']),
                'difficulty' => 'hard',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual campeão é um ladrão e vigarista que vive de apostas e truques em Águas de Sentina?',
                'correct_answer' => 'Twisted Fate',
                'options' => json_encode(['Graves', 'Pyke', 'Twisted Fate', 'Nautilus']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],

            // Bandópolis (region_id 2)
            [
                'text' => 'Qual campeão de Bandópolis é um mestre dos cogumelos e armadilhas?',
                'correct_answer' => 'Teemo',
                'options' => json_encode(['Corki', 'Tristana', 'Lulu', 'Teemo']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é a criatura de Bandópolis que é um dos mais antigos espíritos de Runeterra?',
                'correct_answer' => 'Kindred',
                'options' => json_encode(['Bard', 'Kindred', 'Tahm Kench', 'Ekko']),
                'difficulty' => 'medium',
                'region_id' => 2,
            ],
            [
                'text' => 'Quem é a yordle encantadora que usa magia para invocar ajudantes e dar vida a objetos?',
                'correct_answer' => 'Lulu',
                'options' => json_encode(['Lulu', 'Poppy', 'Vex', 'Yuumi']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual campeão é um inventor yordle que pilota um helicóptero e lança bombas?',
                'correct_answer' => 'Corki',
                'options' => json_encode(['Heimerdinger', 'Teemo', 'Corki', 'Ziggs']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é a criatura de Bandópolis que é um dos mais antigos espíritos de Runeterra?',
                'correct_answer' => 'Kindred',
                'options' => json_encode(['Bard', 'Kindred', 'Tahm Kench', 'Ekko']),
                'difficulty' => 'medium',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual campeão é o protetor de Bandópolis, um guerreiro corajoso que empunha um escudo e um martelo?',
                'correct_answer' => 'Poppy',
                'options' => json_encode(['Gnar', 'Rumble', 'Poppy', 'Teemo']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é o nome da academia de magia de Bandópolis, onde os yordles aprendem a usar seus poderes?',
                'correct_answer' => 'A Academia Yordle de Bandópolis',
                'options' => json_encode(['A Academia de Yordle de Bandópolis', 'O Colégio de Bandópolis', 'A Escola de Magia de Bandópolis', 'O Templo de Bandópolis']),
                'difficulty' => 'hard',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é o nome da arma de Tristana?',
                'correct_answer' => 'Pistola de canhão',
                'options' => json_encode(['Pistola de canhão', 'Arco e flecha', 'Espada', 'Martelo']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual campeão é um yordle mago que lança bombas e constrói engenhocas para defender Bandópolis?',
                'correct_answer' => 'Ziggs',
                'options' => json_encode(['Heimerdinger', 'Rumble', 'Teemo', 'Ziggs']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual campeão é um yordle que se transforma em um monstro peludo quando está com raiva?',
                'correct_answer' => 'Gnar',
                'options' => json_encode(['Teemo', 'Corki', 'Heimerdinger', 'Gnar']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],

            // Demacia (region_id 3)
            [
                'text' => 'Qual campeão de Demacia é um príncipe, herdeiro do trono e um guerreiro leal?',
                'correct_answer' => 'Jarvan IV',
                'options' => json_encode(['Garen', 'Jarvan IV', 'Sylas', 'Lux']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual é o nome da família real de Demacia?',
                'correct_answer' => 'Família Escudo de Luz',
                'options' => json_encode(['Família Escudo de Luz', 'Família da Coroa', 'Família da Chama', 'Família da Lua']),
                'difficulty' => 'medium',
                'region_id' => 3,
            ],
            [
                'text' => 'Quem é o "Poder de Demacia", um guerreiro com uma grande espada que defende os ideais do reino?',
                'correct_answer' => 'Garen',
                'options' => json_encode(['Jarvan IV', 'Garen', 'Sylas', 'Lux']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual campeão é um caçador de magos que usa algemas de petricita para prender e absorver magia?',
                'correct_answer' => 'Sylas',
                'options' => json_encode(['Garen', 'Lux', 'Sylas', 'Jarvan IV']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual campeã é uma maga que usa luz para curar e atacar?',
                'correct_answer' => 'Lux',
                'options' => json_encode(['Garen', 'Sylas', 'Lux', 'Fiora']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual campeão é um lutador que defende os ideais de honra e justiça de Demacia?',
                'correct_answer' => 'Garen',
                'options' => json_encode(['Jarvan IV', 'Garen', 'Fiora', 'Lux']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual é o nome do mineral raro que é usado para construir as muralhas de Demacia e que é resistente à magia?',
                'correct_answer' => 'Petricita',
                'options' => json_encode(['Petricita', 'Magia da Luz', 'Magia das Trevas', 'Magia da Vida']),
                'difficulty' => 'medium',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual é o lema oficial de Demacia?',
                'correct_answer' => 'Por Demacia!',
                'options' => json_encode(['Por Demacia!', 'A glória de Noxus!', 'Pela luz!', 'Pela honra!']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual campeã é uma esgrimista de Demacia que defende a honra de sua família e se considera a mais hábil de toda a região?',
                'correct_answer' => 'Fiora',
                'options' => json_encode(['Lux', 'Poppy', 'Fiora', 'Shyvana']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual campeão é um dragão que se disfarça de humano para proteger Demacia de ameaças externas?',
                'correct_answer' => 'Shyvana',
                'options' => json_encode(['Garen', 'Jarvan IV', 'Shyvana', 'Kayle']),
                'difficulty' => 'medium',
                'region_id' => 3,
            ],

            // Freljord (region_id 4)
            [
                'text' => 'Qual campeã é a líder da tribo Avarosa e uma grande arqueira de gelo?',
                'correct_answer' => 'Ashe',
                'options' => json_encode(['Sejuani', 'Lissandra', 'Ashe', 'Braum']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Quem é a Rainha do Gelo, uma feiticeira maligna que busca dominar Freljord com seu exército de Trolls de Gelo?',
                'correct_answer' => 'Lissandra',
                'options' => json_encode(['Lissandra', 'Sejuani', 'Ashe', 'Anivia']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual campeão é o "Coração do Freljord", um guerreiro forte e gentil com um grande escudo?',
                'correct_answer' => 'Braum',
                'options' => json_encode(['Olaf', 'Volibear', 'Tryndamere', 'Braum']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual campeão é um urso guerreiro com uma armadura de gelo, que busca proteger Freljord de seus inimigos?',
                'correct_answer' => 'Volibear',
                'options' => json_encode(['Ornn', 'Volibear', 'Anivia', 'Olaf']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual é o nome da tribo de ursos guerreiros de Freljord, liderada por Volibear?',
                'correct_answer' => 'A tribo dos Uivantes',
                'options' => json_encode(['A tribo dos Gélidos', 'A tribo dos Gélidos', 'A tribo dos Uivantes', 'A tribo dos Congelados']),
                'difficulty' => 'hard',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual campeão é o "Rei Bárbaro" de Freljord, um guerreiro que busca vingança por seu povo?',
                'correct_answer' => 'Tryndamere',
                'options' => json_encode(['Olaf', 'Braum', 'Tryndamere', 'Volibear']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Sejuani?',
                'correct_answer' => 'Sivír',
                'options' => json_encode(['Bristle', 'Sivír', 'Avarosa', 'Braumn']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual campeão é o "Forjador de Montanhas", um ferreiro lendário que vive em Freljord?',
                'correct_answer' => 'Ornn',
                'options' => json_encode(['Braum', 'Volibear', 'Anivia', 'Ornn']),
                'difficulty' => 'medium',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual campeã é a líder da tribo dos Garras do Inverno e uma guerreira implacável?',
                'correct_answer' => 'Sejuani',
                'options' => json_encode(['Ashe', 'Lissandra', 'Sejuani', 'Janna']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual é a ave lendária de Freljord que se acredita ser uma das primeiras criaturas de Runeterra?',
                'correct_answer' => 'Anivia',
                'options' => json_encode(['Anivia', 'Sejuani', 'Lissandra', 'Ashe']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],

            // Ilhas das Sombras (region_id 5)
            [
                'text' => 'Qual campeão das Ilhas das Sombras é um cavaleiro espectral com uma grande espada?',
                'correct_answer' => 'Hecarim',
                'options' => json_encode(['Thresh', 'Kalista', 'Mordekaiser', 'Hecarim']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Quem é o "Guardião da Corrente", um demônio que aprisiona almas com sua corrente e lanterna?',
                'correct_answer' => 'Thresh',
                'options' => json_encode(['Thresh', 'Yorick', 'Hecarim', 'Elise']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual campeã é a "Lança da Vingança", um espírito que busca vingança por aqueles que a traíram?',
                'correct_answer' => 'Kalista',
                'options' => json_encode(['Kalista', 'Viego', 'Hecarim', 'Thresh']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual campeão é um rei morto-vivo com um grande exército de fantasmas?',
                'correct_answer' => 'Mordekaiser',
                'options' => json_encode(['Hecarim', 'Mordekaiser', 'Viego', 'Yorick']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual campeão é o "Coveiro", um monge solitário que carrega uma pá e um grande exército de mortos-vivos?',
                'correct_answer' => 'Yorick',
                'options' => json_encode(['Hecarim', 'Thresh', 'Yorick', 'Mordekaiser']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual é o nome da feiticeira que se tornou uma criatura maligna com a ajuda de um artefato mágico?',
                'correct_answer' => 'Viego',
                'options' => json_encode(['Viego', 'Elise', 'Kalista', 'Gwen']),
                'difficulty' => 'medium',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual é a criatura de Ilhas das Sombras que é uma aranha gigante e uma feiticeira malvada?',
                'correct_answer' => 'Elise',
                'options' => json_encode(['Elise', 'Kalista', 'Hecarim', 'Mordekaiser']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual é o nome da espada de Kalista?',
                'correct_answer' => 'A Lança da Vingança',
                'options' => json_encode(['A Lança da Vingança', 'O Martelo da Vingança', 'O Machado da Vingança', 'A Espada da Vingança']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual campeão é uma alma perturbada que busca redenção por seus pecados?',
                'correct_answer' => 'Amumu',
                'options' => json_encode(['Amumu', 'Thresh', 'Yorick', 'Mordekaiser']),
                'difficulty' => 'medium',
                'region_id' => 5,
            ],
            [
                'text' => 'Qual campeã é uma costureira de bonecas que se tornou um espírito para proteger sua criação?',
                'correct_answer' => 'Gwen',
                'options' => json_encode(['Viego', 'Elise', 'Gwen', 'Kalista']),
                'difficulty' => 'easy',
                'region_id' => 5,
            ],

            // Ionia (region_id 6)
            [
                'text' => 'Qual campeão de Ionia é um assassino habilidoso com uma grande foice?',
                'correct_answer' => 'Zed',
                'options' => json_encode(['Yasuo', 'Lee Sin', 'Shen', 'Zed']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Quem é o "Caminho do Dragão", um monge cego que usa seus punhos para lutar?',
                'correct_answer' => 'Lee Sin',
                'options' => json_encode(['Akali', 'Shen', 'Lee Sin', 'Yasuo']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeã é a "Sombra do Vento", uma assassina com duas lâminas que busca vingança por seu povo?',
                'correct_answer' => 'Akali',
                'options' => json_encode(['Syndra', 'Ahri', 'Irelia', 'Akali']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeão é um guerreiro samurai com uma espada lendária, que busca redenção por seus pecados?',
                'correct_answer' => 'Yasuo',
                'options' => json_encode(['Yasuo', 'Zed', 'Shen', 'Lee Sin']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual é o nome da antiga espada de Master Yi?',
                'correct_answer' => 'O Sabre Sagrado',
                'options' => json_encode(['A Espada do Dragão', 'A Espada da Lua', 'O Sabre Sagrado', 'A Espada do Sol']),
                'difficulty' => 'medium',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeão é um guardião de Ionia que usa teletransporte para se mover rapidamente pelo campo de batalha?',
                'correct_answer' => 'Shen',
                'options' => json_encode(['Yasuo', 'Zed', 'Shen', 'Lee Sin']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeã é uma feiticeira de Ionia que usa magia de cura para ajudar seus aliados?',
                'correct_answer' => 'Janna',
                'options' => json_encode(['Soraka', 'Janna', 'Ahri', 'Irelia']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Master Yi?',
                'correct_answer' => 'O coelho de Master Yi',
                'options' => json_encode(['O gato de Master Yi', 'O coelho de Master Yi', 'O cachorro de Master Yi', 'O dragão de Master Yi']),
                'difficulty' => 'hard',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeã é uma dançarina de espadas de Ionia que usa suas lâminas para lutar?',
                'correct_answer' => 'Irelia',
                'options' => json_encode(['Akali', 'Ahri', 'Irelia', 'Syndra']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual campeão é um espírito das trevas que usa magia para invocar sombras?',
                'correct_answer' => 'Syndra',
                'options' => json_encode(['Yasuo', 'Zed', 'Syndra', 'Shen']),
                'difficulty' => 'easy',
                'region_id' => 6,
            ],

            // Ixtal (region_id 7)
            [
                'text' => 'Qual campeão de Ixtal é um elementalista que usa magia para controlar os elementos?',
                'correct_answer' => 'Qiyana',
                'options' => json_encode(['Rengar', 'Nidalee', 'Qiyana', 'Ivern']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],
            [
                'text' => 'Quem é o "Caçador da Noite", um caçador de monstros com uma grande espada?',
                'correct_answer' => 'Rengar',
                'options' => json_encode(['Kha\'Zix', 'Nidalee', 'Rengar', 'Ivern']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual campeão é uma guardiã da natureza que se transforma em uma pantera?',
                'correct_answer' => 'Nidalee',
                'options' => json_encode(['Skarner', 'Zyra', 'Nidalee', 'Qiyana']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual é a criatura de Ixtal que é um caranguejo gigante e um guardião da natureza?',
                'correct_answer' => 'Skarner',
                'options' => json_encode(['Skarner', 'Zyra', 'Ivern', 'Qiyana']),
                'difficulty' => 'medium',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual campeão é um elementalista que usa magia de gelo para congelar seus inimigos?',
                'correct_answer' => 'Braum',
                'options' => json_encode(['Skarner', 'Zyra', 'Ivern', 'Braum']),
                'difficulty' => 'medium',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual é o nome da cidade de Ixtal que é protegida por uma barreira de árvores?',
                'correct_answer' => 'Ixaocan',
                'options' => json_encode(['Ixaocan', 'Oasis', 'Templo de Ixtal', 'Cidade da Floresta']),
                'difficulty' => 'hard',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual campeã é uma feiticeira que usa magia da natureza para controlar as plantas?',
                'correct_answer' => 'Zyra',
                'options' => json_encode(['Nidalee', 'Ivern', 'Zyra', 'Qiyana']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual campeão é um "Vigarista da Selva", um ladrão de Ixtal que usa magia para se esconder?',
                'correct_answer' => 'Twisted Fate',
                'options' => json_encode(['Twisted Fate', 'Rengar', 'Nidalee', 'Qiyana']),
                'difficulty' => 'medium',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Ivern?',
                'correct_answer' => 'Misterioso',
                'options' => json_encode(['Misterioso', 'Dragão', 'Gato', 'Cachorro']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],
            [
                'text' => 'Qual campeão é um guardião da natureza que usa magia para curar seus aliados?',
                'correct_answer' => 'Ivern',
                'options' => json_encode(['Nidalee', 'Zyra', 'Ivern', 'Qiyana']),
                'difficulty' => 'easy',
                'region_id' => 7,
            ],

            // Noxus (region_id 8)
            [
                'text' => 'Qual campeão de Noxus é um general que lidera um grande exército e busca a glória?',
                'correct_answer' => 'Darius',
                'options' => json_encode(['Darius', 'Swain', 'Katarina', 'Sion']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Quem é a "Mão de Noxus", um guerreiro que usa um grande machado para lutar?',
                'correct_answer' => 'Darius',
                'options' => json_encode(['Sion', 'Darius', 'Swain', 'Katarina']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual campeã é uma assassina que usa adagas para lutar?',
                'correct_answer' => 'Katarina',
                'options' => json_encode(['LeBlanc', 'Cassiopeia', 'Katarina', 'Talon']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual é o nome do líder de Noxus, um general que usa magia negra para controlar seus inimigos?',
                'correct_answer' => 'Swain',
                'options' => json_encode(['Darius', 'Swain', 'Sion', 'Katarina']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual campeão é um guerreiro imortal que usa uma grande espada e um escudo?',
                'correct_answer' => 'Sion',
                'options' => json_encode(['Urgot', 'Sion', 'Darius', 'Swain']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual campeã é uma feiticeira que usa magia negra para controlar seus inimigos?',
                'correct_answer' => 'LeBlanc',
                'options' => json_encode(['LeBlanc', 'Cassiopeia', 'Katarina', 'Talon']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Urgot?',
                'correct_answer' => 'O caranguejo de Urgot',
                'options' => json_encode(['O dragão de Urgot', 'O caranguejo de Urgot', 'O cachorro de Urgot', 'O gato de Urgot']),
                'difficulty' => 'hard',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual campeão é um "Vigilante", um guerreiro que usa uma armadura de metal para lutar?',
                'correct_answer' => 'Urgot',
                'options' => json_encode(['Darius', 'Urgot', 'Sion', 'Swain']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual campeão é um guerreiro que usa uma grande espada para lutar e busca a glória?',
                'correct_answer' => 'Darius',
                'options' => json_encode(['Sion', 'Darius', 'Swain', 'Katarina']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual é o nome do irmão de Katarina?',
                'correct_answer' => 'Talon',
                'options' => json_encode(['Darius', 'Swain', 'Talon', 'Katarina']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],

            // Piltover (region_id 9)
            [
                'text' => 'Qual campeã de Piltover é uma xerife que usa um rifle de precisão para lutar?',
                'correct_answer' => 'Caitlyn',
                'options' => json_encode(['Vi', 'Jinx', 'Caitlyn', 'Jayce']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Quem é o "Guardião do Amanhã", um inventor que usa uma grande arma para lutar?',
                'correct_answer' => 'Jayce',
                'options' => json_encode(['Ekko', 'Jayce', 'Heimerdinger', 'Viktor']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeã é uma detetive que usa suas luvas de metal para lutar?',
                'correct_answer' => 'Vi',
                'options' => json_encode(['Caitlyn', 'Jinx', 'Vi', 'Heimerdinger']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual é o nome do cientista louco que usa magia e tecnologia para construir seus artefatos?',
                'correct_answer' => 'Heimerdinger',
                'options' => json_encode(['Viktor', 'Heimerdinger', 'Jayce', 'Ezreal']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeão é um "Explorador Pródigo" que usa uma luva mágica para lutar?',
                'correct_answer' => 'Ezreal',
                'options' => json_encode(['Jayce', 'Ezreal', 'Heimerdinger', 'Vi']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeã é uma maga que usa magia de cura para ajudar seus aliados?',
                'correct_answer' => 'Janna',
                'options' => json_encode(['Janna', 'Soraka', 'Ahri', 'Irelia']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Ezreal?',
                'correct_answer' => 'O gorila de Ezreal',
                'options' => json_encode(['O cachorro de Ezreal', 'O gato de Ezreal', 'O gorila de Ezreal', 'O dragão de Ezreal']),
                'difficulty' => 'hard',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeão é um "Robô de Piltover", um guardião de metal que defende a cidade?',
                'correct_answer' => 'Blitzcrank',
                'options' => json_encode(['Orianna', 'Viktor', 'Blitzcrank', 'Ezreal']),
                'difficulty' => 'medium',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeã é uma dançarina de espadas de Piltover que usa suas lâminas para lutar?',
                'correct_answer' => 'Irelia',
                'options' => json_encode(['Akali', 'Ahri', 'Irelia', 'Syndra']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual campeão é um inventor que busca a glória e o poder para o seu povo?',
                'correct_answer' => 'Viktor',
                'options' => json_encode(['Viktor', 'Heimerdinger', 'Jayce', 'Ezreal']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],

            // Shurima (region_id 10)
            [
                'text' => 'Qual campeão de Shurima é um imperador que se tornou um dragão de areia?',
                'correct_answer' => 'Azir',
                'options' => json_encode(['Nasus', 'Renekton', 'Sivir', 'Azir']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Quem é o "Cão do Sol", um guerreiro com uma grande espada que busca vingança por seu povo?',
                'correct_answer' => 'Nasus',
                'options' => json_encode(['Renekton', 'Nasus', 'Sivir', 'Azir']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual campeã é uma caçadora de tesouros com uma grande espada?',
                'correct_answer' => 'Sivir',
                'options' => json_encode(['Sivir', 'Cassiopeia', 'Rek\'Sai', 'Azir']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual campeão é um jacaré guerreiro que usa uma grande espada e um escudo?',
                'correct_answer' => 'Renekton',
                'options' => json_encode(['Nasus', 'Renekton', 'Sivir', 'Azir']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual é a criatura de Shurima que é uma aranha gigante e uma feiticeira malvada?',
                'correct_answer' => 'Elise',
                'options' => json_encode(['Elise', 'Kalista', 'Hecarim', 'Mordekaiser']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual é o nome da cidade de Shurima que é protegida por uma barreira de areia?',
                'correct_answer' => 'A cidade de Shurima',
                'options' => json_encode(['A cidade de Shurima', 'Oásis de Shurima', 'O Templo de Shurima', 'A Cidade da Areia']),
                'difficulty' => 'hard',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual campeã é uma feiticeira que usa magia da natureza para controlar as plantas?',
                'correct_answer' => 'Zyra',
                'options' => json_encode(['Nidalee', 'Ivern', 'Zyra', 'Qiyana']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual campeão é um "Vigarista do Deserto", um ladrão de Shurima que usa magia para se esconder?',
                'correct_answer' => 'Twisted Fate',
                'options' => json_encode(['Twisted Fate', 'Rengar', 'Nidalee', 'Qiyana']),
                'difficulty' => 'medium',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual é o nome do animal de estimação de Nasus?',
                'correct_answer' => 'O cachorro de Nasus',
                'options' => json_encode(['O cachorro de Nasus', 'O gato de Nasus', 'O dragão de Nasus', 'O coelho de Nasus']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
            [
                'text' => 'Qual campeão é um espírito das trevas que usa magia para invocar sombras?',
                'correct_answer' => 'Syndra',
                'options' => json_encode(['Yasuo', 'Zed', 'Syndra', 'Shen']),
                'difficulty' => 'easy',
                'region_id' => 10,
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
