<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class QuestionSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            [
                'text' => 'Qual personagem é líder da tribo dos Garras do Inverno?',
                'correct_answer' => 'Sejuani',
                'options' => json_encode(['Ashe', 'Lissandra', 'Sejuani', 'Olaf']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual é o nome da arma de Tristana?',
                'correct_answer' => 'Boomer',
                'options' => json_encode(['Pistola de canhão', 'O Treco Sussurrante', 'Canhão de mão', 'Boomer']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual personagem é um ladrão e vigarista que vive de apostas e truques em Águas de Sentina?',
                'correct_answer' => 'Twisted Fate',
                'options' => json_encode(['Graves', 'Pyke', 'Twisted Fate', 'Nautilus']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual é a moeda local de Águas de Sentina?',
                'correct_answer' => 'Serpente de Prata',
                'options' => json_encode(['Serpente de Prata', 'Moeda de ouro', 'Pedra de fogo', 'Escama de dragão']),
                'difficulty' => 'medium',
                'region_id' => 1,
            ],
            [
                'text' => 'Qual região de Runeterra é o lar do Garen?',
                'correct_answer' => 'Demacia',
                'options' => json_encode(['Ionia', 'Demacia', 'Noxus', 'Freljord']),
                'difficulty' => 'easy',
                'region_id' => 3
            ],
            [
                'text' => 'Qual personagem subiu o monte targon e foi escolhido(a) como receptáculo do aspecto da justiça?',
                'correct_answer' => 'Mihira',
                'options' => json_encode(['Mihira', 'Taric', 'Kayle', 'Leona']),
                'difficulty' => 'hard',
                'region_id' => 11
            ],
            [
                'text' => 'Após ser exilado(a) de Noxus por se opor aos métodos doentios de guerra, qual personagem busca redenção e uma nova vida em Ionia?',
                'correct_answer' => 'Riven',
                'options' => json_encode(['Darius', 'Katarina', 'Riven', 'Talon']),
                'difficulty' => 'medium',
                'region_id' => 6
            ],
            [
                'text' => 'Em qual região Riven foi buscar redenção e uma nova vida em runeterra?',
                'correct_answer' => 'Ionia',
                'options' => json_encode(['Ionia', 'Demacia', 'Ixtal', 'Freljord']),
                'difficulty' => 'easy',
                'region_id' => 6
            ],
            [
                'text' => 'O Monte Targon é a mais imponente montanha de Runeterra, um local onde pessoas são testadas e, se forem dignas, podem se tornar os Avatares das constelações. Qual personagem ascendeu para se tornar o Aspecto do Sol?',
                'correct_answer' => 'Leona',
                'options' => json_encode(['Zoe', 'Leona', 'Taric', 'Pantheon']),
                'difficulty' => 'easy',
                'region_id' => 11
            ],
            [
                'text' => 'Qual personagem é um ser ancestral poderoso e é adorado como um deus da forja por alguns, mas se mantém isolado no coração de uma montanha no Freljord?',
                'correct_answer' => 'Ornn',
                'options' => json_encode(['Volibear', 'Braum', 'Olaf', 'Ornn']),
                'difficulty' => 'hard',
                'region_id' => 4
            ],
            [
                'text' => 'Qiyana, a Imperatriz dos Elementos, governa sobre qual região?',
                'correct_answer' => 'Ixtal',
                'options' => json_encode(['Shurima', 'Ixtal', 'Targon', 'Freljord']),
                'difficulty' => 'easy',
                'region_id' => 7
            ],
            [
                'text' => 'Darius e Swain são líderes militares influentes de qual região?',
                'correct_answer' => 'Noxus',
                'options' => json_encode(['Noxus', 'Demacia', 'Piltover', 'Águas de Sentina']),
                'difficulty' => 'easy',
                'region_id' => 8
            ],
            [
                'text' => 'Em Freljord, a Guerra das Três Irmãs dividiu a região em facções. Quais irmãs protagonizaram esse conflito?',
                'correct_answer' => 'Avarosa, Serylda e Lissandra',
                'options' => json_encode(['Sejuani, Ashe e Lissandra', 'Avarosa, Serylda e Lissandra', 'Anivia, Ashe e Tryndamere', 'Serylda, Ashe e Anivia']),
                'difficulty' => 'medium',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual personagem sugere que lux se case com Jarvan IV para que ela fique a salvo da perseguição por sua magia?',
                'correct_answer' => 'Tianna',
                'options' => json_encode(['Tianna', 'Fiora', 'Garen', 'Jarvan III']),
                'difficulty' => 'hard',
                'region_id' => 3,
            ],
            [
                'text' => 'Qual ordem demaciana é encarregada de conter a magia dentro do país?',
                'correct_answer' => 'Caçadores de Magos',
                'options' => json_encode(['Caçadores de Magos', 'Trifarix', 'Vanguarda Intrépida', 'Vanguarda Destemida']),
                'difficulty' => 'easy',
                'region_id' => 3,
            ],
            [
                'text' => 'Darius e seu irmão Draven cresceram em qual cidade portuária de Noxus?',
                'correct_answer' => 'Basilich',
                'options' => json_encode(['Basilich', 'Drekan', 'Drugne', 'Khworez']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual comandante noxiano reconheceu a força de Darius e seu irmão, recrutando-os para o exército?',
                'correct_answer' => 'Cyrus',
                'options' => json_encode(['Cyrus', 'Boram Darkwill', 'Swain', 'Draven']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Em qual batalha Darius decapitou um general noxiano para evitar a retirada das tropas?',
                'correct_answer' => 'Batalha das Planícies de Dalamor',
                'options' => json_encode(['Batalha das Planícies de Dalamor', 'Cerco de Placidium', 'Batalha de Basilich', 'Guerra das Três Irmãs']),
                'difficulty' => 'hard',
                'region_id' => 8,
            ],
            [
                'text' => 'Após a vitória contra os Varju, que título Darius recebeu do imperador Boram Darkwill?',
                'correct_answer' => 'Mão de Noxus',
                'options' => json_encode(['Mão de Noxus', 'Lâmina de Noxus', 'Punho de Noxus', 'Braço de Noxus']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Quem liderou o golpe que resultou na morte do imperador Boram Darkwill?',
                'correct_answer' => 'Jericho Swain',
                'options' => json_encode(['Jericho Swain', 'Mordekaiser', 'Darius', 'LeBlanc']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Após o golpe, Darius decidiu apoiar qual novo líder de Noxus?',
                'correct_answer' => 'Jericho Swain',
                'options' => json_encode(['Jericho Swain', 'Boram Darkwill', 'LeBlanc', 'Draven']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Com a formação do Trifarix, Darius assumiu qual princípio de força?',
                'correct_answer' => 'Poder',
                'options' => json_encode(['Poder', 'Visão', 'Astúcia', 'Sabedoria']),
                'difficulty' => 'hard',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual legião Darius fundou para representar a elite militar de Noxus?',
                'correct_answer' => 'Legião Trifariana',
                'options' => json_encode(['Legião Trifariana', 'Legião de Ferro', 'Legião de Honra', 'Legião Sombria']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Em qual região Darius foi enviado para subjugar as tribos bárbaras?',
                'correct_answer' => 'Freljord',
                'options' => json_encode(['Freljord', 'Demacia', 'Ionia', 'Shurima']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Durante a campanha em Freljord, Darius enfrentou qual tribo feroz?',
                'correct_answer' => 'Garra do Inverno',
                'options' => json_encode(['Garra do Inverno', 'Garras de Freljord', 'Garras do Norte', 'Garras de Noxus']),
                'difficulty' => 'hard',
                'region_id' => 8,
            ],
            [
                'text' => 'Nos contos, qual das seguintes regiões valoriza mais Lamb em comparação a Wolf?',
                'correct_answer' => 'Demacia',
                'options' => json_encode(['Noxus', 'Demacia', 'Zaun', 'Ionia']),
                'difficulty' => 'hard',
                'region_id' => 3,
            ],
            [
                'text' => 'Nos mitos regionais de Kindred, como são conhecidos Lamb e Wolf na “parte leste”?',
                'correct_answer' => 'Farya e Wolyo',
                'options' => json_encode(['Ina e Ani', 'Farya e Wolyo', 'Lamb e Wolf', 'Lina e Wolo']),
                'difficulty' => 'hard',
                'region_id' => 6,
            ],
            [
                'text' => 'Qual era o sonho que Sion desejava antes de sua morte original?',
                'correct_answer' => 'Glória e a conquista para o império de Noxus',
                'options' => json_encode(['Ter uma família próspera', 'Glória e a conquista para o império de Noxus', 'Viajar além das fronteiras de Noxus', 'Alcançar imortalidade']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'No conto "Sombra e Fortuna", qual personagem de Freljord está presente em Águas de Sentina em busca de uma morte gloriosa em batalha?',
                'correct_answer' => 'Olaf',
                'options' => json_encode(['Lucian', 'Miss Fortune', 'Olaf', 'Thresh']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'No conto "Sombra e Fortuna", a sacerdotisa de Nagacáburos, que adverte Miss Fortune sobre uma tempestade, pertence a qual região?',
                'correct_answer' => 'Águas de Sentina',
                'options' => json_encode(['Ilhas das Sombras', 'Freljord', 'Demacia', 'Águas de Sentina']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'No conto "Sombra e Fortuna", que personagem, emerge da Névoa Negra e aprisiona a alma de um pescador chamado Piet?',
                'correct_answer' => 'Thresh',
                'options' => json_encode(['Hecarim', 'Pyke', 'Thresh', 'Kalista']),
                'difficulty' => 'medium',
                'region_id' => 5,
            ],
            [
                'text' => 'No conto "Sombra e Fortuna", após a queda de Gangplank, qual personagem assumiu a liderança de Águas de Sentina e usa a rivalidade entre gangues para consolidar seu poder?',
                'correct_answer' => 'Miss Fortune',
                'options' => json_encode(['Illaoi', 'Lucian', 'Miss Fortune', 'Braum']),
                'difficulty' => 'easy',
                'region_id' => 1,
            ],
            [
                'text' => 'No conto "Sombra e Fortuna", que entidade de uma região amaldiçoada se aproxima de Águas de Sentina, causando terror na população?',
                'correct_answer' => 'A Névoa Negra',
                'options' => json_encode(['O Vazio', 'O Cão das Areias', 'Um Dragocráquem', 'A Névoa Negra']),
                'difficulty' => 'hard',
                'region_id' => 5,
            ],
            [
                'text' => 'No conto "A Voz da Fornalha", que criatura lendária emerge da fornalha para combater os Ursine?',
                'correct_answer' => 'Ornn',
                'options' => json_encode(['Volibear', 'Anivia', 'Olaf', 'Ornn']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'No conto "A Voz da Fornalha", qual é o nome do líder dos Ursine?',
                'correct_answer' => 'Volibear',
                'options' => json_encode(['Ornn', 'Olaf', 'Gnar', 'Volibear']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'No conto "A Voz da Fornalha", quem atacou a tribo Garra do Inverno?',
                'correct_answer' => 'Ursine',
                'options' => json_encode(['Ursine', 'Filhos do Gelo', 'Barbaros', 'Guerreiros de Noxus']),
                'difficulty' => 'medium',
                'region_id' => 4,
            ],
            [
                'text' => 'No conto "A Voz da Fornalha", a batalha entre Ornn e Volibear é tão intensa que o cenário é transformado por lava e raios. Qual é a região onde este confronto épico acontece?',
                'correct_answer' => 'Freljord',
                'options' => json_encode(['Shurima', 'Ilhas das Sombras', 'Demacia', 'Freljord']),
                'difficulty' => 'easy',
                'region_id' => 4,
            ],
            [
                'text' => 'No conto "A Voz da Fornalha", qual é o nome da cidade em ruínas, que também é o lar de Ornn, onde a história se passa?',
                'correct_answer' => 'Pedra-Lar',
                'options' => json_encode(['Lokfar', 'Freljord', 'Pedra-Lar', 'A Fornalha Sagrada']),
                'difficulty' => 'medium',
                'region_id' => 4,
            ],
            [
                'text' => 'Qual o nome da mãe de Lux que procura um "anulador" para ajudar a "curar" o poder mágico da filha?',
                'correct_answer' => 'Augatha',
                'options' => json_encode(['Giselle', 'Augatha', 'Demacia', 'Olgavanna']),
                'difficulty' => 'hard',
                'region_id' => 3,
            ],
            [
                'text' => 'No conto "Tudo o que deveríamos ter dito", qual é o nome do ex-parceiro de K\'Sante que ele reencontra?',
                'correct_answer' => 'Tope',
                'options' => json_encode(['Ulu', 'Tope', 'Eko', 'Zeki']),
                'difficulty' => 'hard',
                'region_id' => 10,
            ],
            [
                'text' => 'Antes de se tornar o aspecto da guerra, qual era o nome do mortal que ousou escalar o Monte Targon?',
                'correct_answer' => 'Atreus',
                'options' => json_encode(['Leona', 'Taric', 'Atreus', 'Pylas']),
                'difficulty' => 'medium',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual Aspecto de Targon habitou o corpo de Atreus antes de ser derrotado por um Darkin?',
                'correct_answer' => 'O Aspecto da Guerra',
                'options' => json_encode(['O Aspecto do Sol', 'O Aspecto da Lua', 'O Aspecto da Montanha', 'O Aspecto da Guerra']),
                'difficulty' => 'easy',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual campeão Darkin foi o responsável por derrotar o Aspecto da Guerra, libertando Atreus?',
                'correct_answer' => 'Aatrox',
                'options' => json_encode(['Varus', 'Kayn', 'Rhaast', 'Aatrox']),
                'difficulty' => 'medium',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual era o nome do amigo de infância de Atreus, que o acompanhou na escalada do Monte Targon, mas não sobreviveu à jornada?',
                'correct_answer' => 'Pylas',
                'options' => json_encode(['Myles', 'Pylas', 'Iula', 'Korin']),
                'difficulty' => 'hard',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual é o nome do urso de pelúcia de Annie, infundido com o poder da sombra, que se tornou seu protetor?',
                'correct_answer' => 'Tibbers',
                'options' => json_encode(['Gregori', 'Tibbers', 'Bumble', 'Baron']),
                'difficulty' => 'easy',
                'region_id' => 8,
            ],
            [
                'text' => 'Annie é uma órfã poderosa que domina a magia do fogo nas Terras Forasteiras de qual região?',
                'correct_answer' => 'Noxus',
                'options' => json_encode(['Ionia', 'Demacia', 'Noxus', 'Piltover']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'O poder de Annie manifestou-se de forma explosiva pela primeira vez após qual evento trágico em sua família?',
                'correct_answer' => 'A morte de sua mãe',
                'options' => json_encode(['A morte de sua mãe', 'A morte de seu pai', 'O ataque de um urso-gato', 'A destruição de sua casa']),
                'difficulty' => 'medium',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual era o nome da mãe de Annie, uma feiticeira de sombras que faleceu tragicamente em Noxus?',
                'correct_answer' => 'Amoline',
                'options' => json_encode(['Iula', 'Morgana', 'Amoline', 'Cinder']),
                'difficulty' => 'hard',
                'region_id' => 8,
            ],
            [
                'text' => 'Qual é o nome da irmã gêmea de Aphelios, que se comunica com ele telepatamente e fornece suas armas?',
                'correct_answer' => 'Alune',
                'options' => json_encode(['Alune', 'Leona', 'Diana', 'Zoe']),
                'difficulty' => 'easy',
                'region_id' => 11,
            ],
            [
                'text' => 'Aphelios e sua irmã Alune pertencem a qual seita de Targon que adora a lua?',
                'correct_answer' => 'Lunari',
                'options' => json_encode(['Lunari', 'Solari', 'Ascendentes', 'Guerreiros da Montanha']),
                'difficulty' => 'medium',
                'region_id' => 11,
            ],
            [
                'text' => 'Na história, como Aphelios silencia sua própria voz para permitir que sua irmã Alune canalize seu poder através dele?',
                'correct_answer' => 'Bebendo um veneno',
                'options' => json_encode(['Bebendo um veneno', 'Recebendo uma bênção celestial', 'Através de um ritual de sangue', 'Com uma oração sagrada']),
                'difficulty' => 'medium',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual é o nome do templo Lunari onde Alune reside, agindo como um farol para seu irmão Aphelios?',
                'correct_answer' => 'Templo da Lua Cheia',
                'options' => json_encode(['Templo da Lua Cheia', 'Templo do Sol Nascente', 'Templo dos Sete', 'Templo do Crepúsculo']),
                'difficulty' => 'hard',
                'region_id' => 11,
            ],
            [
                'text' => 'Qual é o nome completo do Acrónimo Z.A.C, que deu origem ao nome do campeão?',
                'correct_answer' => 'Zaun Amorphous Combatant',
                'options' => json_encode(['Zaun Animated Creature', 'Zaun Aggressive Catalyst', 'Zaun Amorphous Combatant', 'Zaun Alien Contraband']),
                'difficulty' => 'hard',
                'region_id' => 13,
            ],
            [
                'text' => 'Em qual região de Runeterra Zac foi criado por cientistas para ser uma arma biológica?',
                'correct_answer' => 'Zaun',
                'options' => json_encode(['Piltover', 'Zaun', 'Shurima', 'Vazio']),
                'difficulty' => 'easy',
                'region_id' => 13,
            ],
            [
                'text' => 'Quem criou Zac e o submeteu a testes dolorosos, antes que ele fosse resgatado e adotado por um casal?',
                'correct_answer' => 'Cientistas de Zaun',
                'options' => json_encode(['A Ordem do Vazio', 'Membros da Rosa Negra', 'Cientistas de Zaun', 'A família Jinx']),
                'difficulty' => 'medium',
                'region_id' => 13,
            ],
            [
                'text' => 'Qual foi o propósito original para a criação de Zac, descrito em sua história?',
                'correct_answer' => 'Uma bio-arma de combate',
                'options' => json_encode(['Um dispositivo de limpeza de esgoto', 'Um protótipo de robô Hextech', 'Um assistente de laboratório', 'Uma bio-arma de combate']),
                'difficulty' => 'hard',
                'region_id' => 13,
            ],
            [
                'text' => 'De qual espécie de criatura mística Corki é, vindo de uma cidade além de Piltover?',
                'correct_answer' => 'Yordle',
                'options' => json_encode(['Yordle', 'Vastaya', 'Vazio', 'Seraph']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Em qual região Corki estabeleceu sua vida e carreira como aviador e engenheiro, construindo máquinas voadoras?',
                'correct_answer' => 'Piltover',
                'options' => json_encode(['Piltover', 'Zaun', 'Bandópolis', 'Shurima']),
                'difficulty' => 'easy',
                'region_id' => 9,
            ],
            [
                'text' => 'Qual é o nome do esquadrão de elite de aviadores que Corki criou, responsável por reconhecimento e resgate?',
                'correct_answer' => 'Esquadrão de Reconhecimento e Resgate de Bandópolis',
                'options' => json_encode(['Vingadores de Piltover', 'Águias de Aço', 'Esquadrão de Reconhecimento e Resgate de Bandópolis', 'Guardiões Celestiais']),
                'difficulty' => 'medium',
                'region_id' => 2,
            ],
            [
                'text' => 'Durante o conflito entre Noxus e Ionia, qual foi o papel do esquadrão de Corki?',
                'correct_answer' => 'Realizar missões de reconhecimento sobre o território inimigo',
                'options' => json_encode(['Realizar missões de reconhecimento sobre o território inimigo', 'Transportar suprimentos para os feridos', 'Atacar navios de guerra de Noxus', 'Treinar pilotos para combate aéreo']),
                'difficulty' => 'hard',
                'region_id' => 6,
            ],
            [
                'text' => 'Na história, qual personagem tem uma amizade unilateral com Vex, a chamando de "Vee" e organizando festas de aniversário para ela, mesmo com a irritação de Vex?',
                'correct_answer' => 'Allay',
                'options' => json_encode(['Grimm', 'Norra', 'Allay', 'Yuumi']),
                'difficulty' => 'hard',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é o nome do livro mágico que permite a Yuumi viajar entre o Reino Físico e o Reino Espiritual para procurar sua dona, Norra?',
                'correct_answer' => 'O Livro dos Limiares',
                'options' => json_encode(['O Livro da Ruína', 'O Tomo do Vazio', 'O Livro dos Limiares', 'O Compêndio da Magia']),
                'difficulty' => 'medium',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é o nome da dona da Yuumi?',
                'correct_answer' => 'Norra',
                'options' => json_encode(['Norra', 'Lulu', 'Allay', 'Tristana']),
                'difficulty' => 'easy',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual é o nome do grupo ao qual a tristana pertence?',
                'correct_answer' => 'Bandoartilheiros',
                'options' => json_encode(['Bandoartilheiros', 'Grupo de Operações Especiais', 'X-time', 'Yordles Pistoleiros']),
                'difficulty' => 'medium',
                'region_id' => 2,
            ],
            [
                'text' => 'Qual personagem pertence ao bandoartilheiros e tem uma arma chamada Alice?',
                'correct_answer' => 'Earl',
                'options' => json_encode(['Earl', 'Giselle', 'Teemo', 'Gaspar']),
                'difficulty' => 'hard',
                'region_id' => 2,
            ],
        ];

        foreach ($questions as $question) {
            Question::create($question);
        }
    }
}
