version: "3.9"

services:
  laravel_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - laravel

  node_app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: node_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "5173:5173" # Vite Dev Server
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    networks:
      - laravel
    depends_on:
      - laravel_app

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
